### ISSUE TITLE
Tests run in different order - 02_array_spec

### ISSUE THREAD

**Issue by andrewjh271** [rlmoser99/ruby_rspec_TOP#3]
For this line, `# Why do you think they are in a different order than these tests are written?`, is the answer that the test not within a context block goes first? I wasn't sure. I think it would be helpful to students if at the end of the document you could include the answer.

**Comment by rlmoser99** [comment]
Great idea! Essentially you are correct. I'll add an explanation at the end of the file.

**Comment by rlmoser99** [comment]
The end of the file seemed out of place for the answer, so I inserted the explanation immediately after the question.
